using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text;

public class ExtractSeedOffsets
{
    [MenuItem("Build/Extract Seed Offsets")]
    public static void Extract()
    {
        string[] testSeeds = { "HHcLC5acQt", "42", "TestSeed123" };
        StringBuilder sb = new StringBuilder();
        
        sb.AppendLine("// AUTO-GENERATED: Unity Random offset values for test seeds");
        sb.AppendLine("// Generated by ExtractSeedOffsets.cs");
        sb.AppendLine("// Unity Version: " + Application.unityVersion);
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace WorldZones.WorldGen");
        sb.AppendLine("{");
        sb.AppendLine("    public static class UnitySeedOffsets");
        sb.AppendLine("    {");
        sb.AppendLine("        // Offsets generated by Unity's Random.InitState() for known seeds");
        sb.AppendLine("        public static readonly Dictionary<string, (double offset0, double offset1, double offset2, double offset3, double offset4)> KnownOffsets = new()");
        sb.AppendLine("        {");
        
        foreach (var seed in testSeeds)
        {
            int seedHash = GetStableHashCode(seed);
            Random.InitState(seedHash);
            
            double offset0 = Random.value * 100000.0;
            double offset1 = Random.value * 100000.0;
            double offset2 = Random.value * 100000.0;
            double offset3 = Random.value * 100000.0;
            double offset4 = Random.value * 100000.0;
            
            Debug.Log($"Seed: {seed}");
            Debug.Log($"  Hash: {seedHash}");
            Debug.Log($"  Offsets: {offset0:F10}, {offset1:F10}, {offset2:F10}, {offset3:F10}, {offset4:F10}");
            
            sb.AppendLine($"            {{ \"{seed}\", ({offset0:G17}, {offset1:G17}, {offset2:G17}, {offset3:G17}, {offset4:G17}) }},");
        }
        
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        
        string outputPath = Path.Combine(Application.dataPath, "..", "..", "src", "WorldZones.WorldGen", "UnitySeedOffsets.cs");
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath));
        File.WriteAllText(outputPath, sb.ToString());
        
        Debug.Log($"✓ Offsets extracted to: {Path.GetFullPath(outputPath)}");
        
        EditorUtility.RevealInFinder(outputPath);
    }
    
    private static int GetStableHashCode(string str)
    {
        int hash1 = 5381;
        int hash2 = hash1;
        
        for (int i = 0; i < str.Length; i++)
        {
            int c = str[i];
            if (i % 2 == 0)
                hash1 = ((hash1 << 5) + hash1) ^ c;
            else
                hash2 = ((hash2 << 5) + hash2) ^ c;
        }
        
        return hash1 + (hash2 * 1566083941);
    }
}
