using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text;

public class ExtractPerlinData
{
    [MenuItem("Build/Extract Perlin Permutation Table")]
    public static void ExtractPermutationTable()
    {
        // Sample Unity's PerlinNoise at known coordinates to reverse-engineer the permutation table
        StringBuilder sb = new StringBuilder();
        
        sb.AppendLine("// Unity PerlinNoise sample data for reverse engineering");
        sb.AppendLine("// Generated by ExtractPerlinData.cs");
        sb.AppendLine();
        
        // Sample a grid of values
        sb.AppendLine("public static class UnityPerlinSamples");
        sb.AppendLine("{");
        sb.AppendLine("    // Sample grid: 0.0 to 10.0 in steps of 0.5");
        sb.AppendLine("    public static readonly float[,] Samples = new float[,]");
        sb.AppendLine("    {");
        
        for (float y = 0; y <= 10f; y += 0.5f)
        {
            sb.Append("        { ");
            for (float x = 0; x <= 10f; x += 0.5f)
            {
                float value = Mathf.PerlinNoise(x, y);
                sb.Append($"{value:F10}f");
                if (x < 10f)
                    sb.Append(", ");
            }
            sb.AppendLine(y < 10f ? " }," : " }");
        }
        
        sb.AppendLine("    };");
        sb.AppendLine();
        
        // Also sample some specific test coordinates
        sb.AppendLine("    // Specific test coordinates");
        sb.AppendLine("    public static readonly (float x, float y, float result)[] TestCoordinates = new[]");
        sb.AppendLine("    {");
        
        float[] testCoords = { 0f, 0.123f, 0.321f, 1.0f, 5.5f, 10.0f, 100.0f, 1000.0f };
        foreach (var x in testCoords)
        {
            foreach (var y in testCoords)
            {
                float result = Mathf.PerlinNoise(x, y);
                sb.AppendLine($"        ({x:F3}f, {y:F3}f, {result:F10}f),");
            }
        }
        
        sb.AppendLine("    };");
        sb.AppendLine("}");
        
        // Write to file
        string outputPath = Path.Combine(Application.dataPath, "..", "Build", "UnityPerlinSamples.cs");
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath));
        File.WriteAllText(outputPath, sb.ToString());
        
        Debug.Log($"Permutation table data extracted to: {Path.GetFullPath(outputPath)}");
        Debug.Log($"Total samples: {(21 * 21) + (testCoords.Length * testCoords.Length)}");
    }
}
