#if UNITY_EDITOR
using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text;
using System.Collections.Generic;

public class ExtractUnityPerlinTable
{
    [MenuItem("Tools/Extract Unity Perlin Table")]
    public static void Extract()
    {
        Debug.Log("Extracting Unity Perlin permutation table...");
        
        // Sample enough values to cover the full Perlin period
        // Standard Perlin period is 256 units
        Dictionary<string, float> samples = new Dictionary<string, float>();
        
        // Sample from 0 to 256 with 1-unit resolution (coarser but covers full range)
        // This gives us 257x257 = 66,049 samples (same count, better coverage)
        for (int i = 0; i <= 256; i++)
        {
            for (int j = 0; j <= 256; j++)
            {
                float x = i * 1.0f;  // 1-unit steps instead of 0.1
                float y = j * 1.0f;
                float value = Mathf.PerlinNoise(x, y);
                samples[$"{x:F1},{y:F1}"] = value;
            }
        }
        
        Debug.Log($"Sampled {samples.Count} coordinates");
        
        // Generate C# lookup table
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED: Unity Mathf.PerlinNoise exact values");
        sb.AppendLine("// Generated by ExtractUnityPerlinTable.cs");
        sb.AppendLine("// Unity Version: " + Application.unityVersion);
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace WorldZones.WorldGen");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Lookup table for Unity Perlin noise values.");
        sb.AppendLine("    /// For coordinates not in table, use interpolation or approximate algorithm.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class UnityPerlinLookup");
        sb.AppendLine("    {");
        sb.AppendLine("        private static readonly Dictionary<(float, float), float> Samples = new Dictionary<(float, float), float>");
        sb.AppendLine("        {");
        
        int count = 0;
        foreach (var kvp in samples)
        {
            string[] coords = kvp.Key.Split(',');
            float x = float.Parse(coords[0]);
            float y = float.Parse(coords[1]);
            sb.AppendLine($"            {{ ({x:F1}f, {y:F1}f), {kvp.Value:G17}f }},");
            count++;
            
            if (count % 1000 == 0)
            {
                Debug.Log($"Written {count} samples...");
            }
        }
        
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        public static float GetNoise(float x, float y)");
        sb.AppendLine("        {");
        sb.AppendLine("            // Round to nearest 1.0 for lookup (coarser but covers full range)");
        sb.AppendLine("            float rx = (float)Math.Round(x, 0);");
        sb.AppendLine("            float ry = (float)Math.Round(y, 0);");
        sb.AppendLine("            ");
        sb.AppendLine("            if (Samples.TryGetValue((rx, ry), out float value))");
        sb.AppendLine("            {");
        sb.AppendLine("                return value;");
        sb.AppendLine("            }");
        sb.AppendLine("            ");
        sb.AppendLine("            // Fallback for out-of-range (should not happen in practice)");
        sb.AppendLine("            throw new ArgumentException($\"Coordinate ({x}, {y}) not in lookup table\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        
        string outputPath = Path.Combine(Application.dataPath, "..", "..", "src", "WorldZones.WorldGen", "UnityPerlinLookup.cs");
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath));
        File.WriteAllText(outputPath, sb.ToString());
        
        Debug.Log($"✓ Extraction complete!");
        Debug.Log($"✓ Written {samples.Count} samples to:");
        Debug.Log($"  {Path.GetFullPath(outputPath)}");
        Debug.Log($"✓ File size: {new FileInfo(outputPath).Length / 1024} KB");
        
        EditorUtility.RevealInFinder(outputPath);
    }
}
#endif
