// AUTO-GENERATED: Unity Random offset values for test seeds
// Generated by ExtractSeedOffsets.cs
// Unity Version: 6000.3.8f1

using System.Collections.Generic;

namespace WorldZones.WorldGen
{
    public static class UnitySeedOffsets
    {
        // Offsets generated by Unity's Random.InitState() for known seeds
        public static readonly Dictionary<string, (double offset0, double offset1, double offset2, double offset3, double offset4)> KnownOffsets = new()
        {
            { "HHcLC5acQt", (20292.78576374054, 64034.789800643921, 71026.712656021118, 6663.8357937335968, 38212.889432907104) },
            { "42", (50223.356485366821, 67149.168252944946, 78337.228298187256, 50808.781385421753, 88518.011569976807) },
            { "TestSeed123", (93832.814693450928, 12742.115557193756, 862.20512166619301, 62151.998281478882, 40036.290884017944) },
        };
    }
}
